In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r'C:\data_science\dataset\atlas2010.csv', delimiter=',')

In [3]:
df.head()

,ano,uf,mun,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,pia18m,pop,popt,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa
0,2010,Rondonia,1100015,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.8,25.49,...,16431,24097,22429,0.00,1.0,1.00,1.00,1.0,1.00,"1,1"
1,2010,Rondonia,1100023,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.2,20.53,...,60213,89766,88730,1.00,1.0,1.00,0.60,1.0,1.00,"2,1"
2,2010,Rondonia,1100031,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.8,26.58,...,4306,6303,6156,0.00,0.7,0.65,1.00,1.0,0.65,"3,1"
3,2010,Rondonia,1100049,cacoal,cacoal,leste rondoniense,74.27,1.90,14.3,15.38,...,54356,78141,76876,0.00,1.0,1.00,0.62,1.0,1.00,"4,1"
4,2010,Rondonia,1100056,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.1,19.42,...,11786,16942,16815,0.43,1.0,1.00,1.00,1.0,1.00,"5,1"

In [4]:
df = df.set_index('mun')
df

,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,razdep,...,pia18m,pop,popt,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa
mun,,,,,,,,,,,,,,,,,,,,,
1100015,2010,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,47.37,...,16431,24097,22429,0.00,1.0,1.00,1.00,1.0,1.00,"1,1"
1100023,2010,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,46.68,...,60213,89766,88730,1.00,1.0,1.00,0.60,1.0,1.00,"2,1"
1100031,2010,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,48.12,...,4306,6303,6156,0.00,0.7,0.65,1.00,1.0,0.65,"3,1"
1100049,2010,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,43.79,...,54356,78141,76876,0.00,1.0,1.00,0.62,1.0,1.00,"4,1"
1100056,2010,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,45.67,...,11786,16942,16815,0.43,1.0,1.00,1.00,1.0,1.00,"5,1"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5222005,2010,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,45.11,...,8914,12501,12445,0.00,1.0,1.00,1.00,1.0,0.71,"5561,1"
5222054,2010,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,42.38,...,5190,7288,7239,0.00,1.0,1.00,1.00,1.0,1.00,"5562,1"
5222203,2010,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,50.80,...,3065,4685,4531,0.00,1.0,1.00,1.00,1.0,1.00,"5563,1"
5222302,2010,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,50.75,...,3476,4739,4523,0.33,1.0,1.00,1.00,1.0,1.00,"5564,1"
5300108,2010,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,40.14,...,1830940,2543802,2541714,1.00,1.0,1.00,1.00,1.0,1.00,"5565,1"

In [5]:
df.loc[1100049]

ano                        2010
uf                     Rondonia
nome_mun                 cacoal
nome_micro               cacoal
nome_meso     leste rondoniense
                    ...
idhm                        1.0
idhm_e                     0.62
idhm_l                      1.0
idhm_r                      1.0
falsa                       4,1
Name: 1100049, Length: 238, dtype: object

In [6]:
df = df.reset_index()
df

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,pia18m,pop,popt,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa
0,1100015,2010,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,16431,24097,22429,0.00,1.0,1.00,1.00,1.0,1.00,"1,1"
1,1100023,2010,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,60213,89766,88730,1.00,1.0,1.00,0.60,1.0,1.00,"2,1"
2,1100031,2010,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,4306,6303,6156,0.00,0.7,0.65,1.00,1.0,0.65,"3,1"
3,1100049,2010,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,54356,78141,76876,0.00,1.0,1.00,0.62,1.0,1.00,"4,1"
4,1100056,2010,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,11786,16942,16815,0.43,1.0,1.00,1.00,1.0,1.00,"5,1"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,8914,12501,12445,0.00,1.0,1.00,1.00,1.0,0.71,"5561,1"
5561,5222054,2010,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,5190,7288,7239,0.00,1.0,1.00,1.00,1.0,1.00,"5562,1"
5562,5222203,2010,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,3065,4685,4531,0.00,1.0,1.00,1.00,1.0,1.00,"5563,1"
5563,5222302,2010,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,3476,4739,4523,0.33,1.0,1.00,1.00,1.0,1.00,"5564,1"
5564,5300108,2010,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,1830940,2543802,2541714,1.00,1.0,1.00,1.00,1.0,1.00,"5565,1"

In [8]:
df.loc[df['espvida'] > 78.5, ['espvida', 'nome_mun', 'nome_meso']]

      espvida            nome_mun             nome_meso
4336    78.62  balneário camboriú        vale do itajaí
4346    78.64            blumenau        vale do itajaí
4357    78.64             brusque        vale do itajaí
4521    78.59     rancho queimado  grande florianópolis
4524    78.52        rio do oeste        vale do itajaí
4526    78.61          rio do sul        vale do itajaí

In [9]:
df.iloc[0:4, 0:3]

       mun   ano        uf
0  1100015  2010  Rondonia
1  1100023  2010  Rondonia
2  1100031  2010  Rondonia
3  1100049  2010  Rondonia

In [10]:
df['classificacao_fectot'] = df['fectot'].apply(lambda x: 'maior' if x >= 2 else 'menor')
df

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,pop,popt,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot
0,1100015,2010,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,24097,22429,0.00,1.0,1.00,1.00,1.0,1.00,"1,1",maior
1,1100023,2010,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,89766,88730,1.00,1.0,1.00,0.60,1.0,1.00,"2,1",menor
2,1100031,2010,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,6303,6156,0.00,0.7,0.65,1.00,1.0,0.65,"3,1",maior
3,1100049,2010,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,78141,76876,0.00,1.0,1.00,0.62,1.0,1.00,"4,1",menor
4,1100056,2010,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,16942,16815,0.43,1.0,1.00,1.00,1.0,1.00,"5,1",maior
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,12501,12445,0.00,1.0,1.00,1.00,1.0,0.71,"5561,1",maior
5561,5222054,2010,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,7288,7239,0.00,1.0,1.00,1.00,1.0,1.00,"5562,1",maior
5562,5222203,2010,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,4685,4531,0.00,1.0,1.00,1.00,1.0,1.00,"5563,1",maior
5563,5222302,2010,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,4739,4523,0.33,1.0,1.00,1.00,1.0,1.00,"5564,1",maior
5564,5300108,2010,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,2543802,2541714,1.00,1.0,1.00,1.00,1.0,1.00,"5565,1",menor

In [11]:
mapeamento = {'maior': 1, 'menor': 0}

In [12]:
df['mapeado'] = df['classificacao_fectot'].map(mapeamento)
df

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,popt,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado
0,1100015,2010,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,22429,0.00,1.0,1.00,1.00,1.0,1.00,"1,1",maior,1
1,1100023,2010,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,88730,1.00,1.0,1.00,0.60,1.0,1.00,"2,1",menor,0
2,1100031,2010,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,6156,0.00,0.7,0.65,1.00,1.0,0.65,"3,1",maior,1
3,1100049,2010,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,76876,0.00,1.0,1.00,0.62,1.0,1.00,"4,1",menor,0
4,1100056,2010,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,16815,0.43,1.0,1.00,1.00,1.0,1.00,"5,1",maior,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,12445,0.00,1.0,1.00,1.00,1.0,0.71,"5561,1",maior,1
5561,5222054,2010,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,7239,0.00,1.0,1.00,1.00,1.0,1.00,"5562,1",maior,1
5562,5222203,2010,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,4531,0.00,1.0,1.00,1.00,1.0,1.00,"5563,1",maior,1
5563,5222302,2010,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,4523,0.33,1.0,1.00,1.00,1.0,1.00,"5564,1",maior,1
5564,5300108,2010,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,2541714,1.00,1.0,1.00,1.00,1.0,1.00,"5565,1",menor,0

In [13]:
df['diferenca'] = 2025 - df['ano']
df

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,i_escolaridade,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado,diferenca
0,1100015,2010,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,0.00,1.0,1.00,1.00,1.0,1.00,"1,1",maior,1,15
1,1100023,2010,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,1.00,1.0,1.00,0.60,1.0,1.00,"2,1",menor,0,15
2,1100031,2010,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,0.00,0.7,0.65,1.00,1.0,0.65,"3,1",maior,1,15
3,1100049,2010,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,0.00,1.0,1.00,0.62,1.0,1.00,"4,1",menor,0,15
4,1100056,2010,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,0.43,1.0,1.00,1.00,1.0,1.00,"5,1",maior,1,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,0.00,1.0,1.00,1.00,1.0,0.71,"5561,1",maior,1,15
5561,5222054,2010,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,0.00,1.0,1.00,1.00,1.0,1.00,"5562,1",maior,1,15
5562,5222203,2010,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,0.00,1.0,1.00,1.00,1.0,1.00,"5563,1",maior,1,15
5563,5222302,2010,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,0.33,1.0,1.00,1.00,1.0,1.00,"5564,1",maior,1,15
5564,5300108,2010,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,1.00,1.0,1.00,1.00,1.0,1.00,"5565,1",menor,0,15

In [14]:
df['diferenca'] = df['diferenca'].astype(int)

In [15]:
df['ano'] = pd.to_datetime(df['ano'], format='%Y')

In [16]:
df['ano']

0      2010-01-01
1      2010-01-01
2      2010-01-01
3      2010-01-01
4      2010-01-01
          ...
5560   2010-01-01
5561   2010-01-01
5562   2010-01-01
5563   2010-01-01
5564   2010-01-01
Name: ano, Length: 5565, dtype: datetime64[ns]

In [17]:
df['ano'].dt.year

0       2010
1       2010
2       2010
3       2010
4       2010
        ...
5560    2010
5561    2010
5562    2010
5563    2010
5564    2010
Name: ano, Length: 5565, dtype: int32

In [18]:
df['ano'].dt.day

0       1
1       1
2       1
3       1
4       1
       ..
5560    1
5561    1
5562    1
5563    1
5564    1
Name: ano, Length: 5565, dtype: int32

In [19]:
df['dia'] = df['ano'].dt.day
df

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado,diferenca,dia
0,1100015,2010-01-01,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,1.0,1.00,1.00,1.0,1.00,"1,1",maior,1,15,1
1,1100023,2010-01-01,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,1.0,1.00,0.60,1.0,1.00,"2,1",menor,0,15,1
2,1100031,2010-01-01,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,0.7,0.65,1.00,1.0,0.65,"3,1",maior,1,15,1
3,1100049,2010-01-01,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,1.0,1.00,0.62,1.0,1.00,"4,1",menor,0,15,1
4,1100056,2010-01-01,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,1.0,1.00,1.00,1.0,1.00,"5,1",maior,1,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010-01-01,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,1.0,1.00,1.00,1.0,0.71,"5561,1",maior,1,15,1
5561,5222054,2010-01-01,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,1.0,1.00,1.00,1.0,1.00,"5562,1",maior,1,15,1
5562,5222203,2010-01-01,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,1.0,1.00,1.00,1.0,1.00,"5563,1",maior,1,15,1
5563,5222302,2010-01-01,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,1.0,1.00,1.00,1.0,1.00,"5564,1",maior,1,15,1
5564,5300108,2010-01-01,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,1.0,1.00,1.00,1.0,1.00,"5565,1",menor,0,15,1

In [20]:
df.iloc[[0]]

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado,diferenca,dia
0,1100015,2010-01-01,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.8,25.49,...,1.0,1.0,1.0,1.0,1.0,"1,1",maior,1,15,1

In [21]:
df_duplo = pd.concat([df, df.iloc[[0]]])

In [22]:
df_duplo

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado,diferenca,dia
0,1100015,2010-01-01,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,1.0,1.00,1.00,1.0,1.00,"1,1",maior,1,15,1
1,1100023,2010-01-01,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,1.0,1.00,0.60,1.0,1.00,"2,1",menor,0,15,1
2,1100031,2010-01-01,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,0.7,0.65,1.00,1.0,0.65,"3,1",maior,1,15,1
3,1100049,2010-01-01,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,1.0,1.00,0.62,1.0,1.00,"4,1",menor,0,15,1
4,1100056,2010-01-01,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,1.0,1.00,1.00,1.0,1.00,"5,1",maior,1,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5561,5222054,2010-01-01,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,1.0,1.00,1.00,1.0,1.00,"5562,1",maior,1,15,1
5562,5222203,2010-01-01,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,1.0,1.00,1.00,1.0,1.00,"5563,1",maior,1,15,1
5563,5222302,2010-01-01,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,1.0,1.00,1.00,1.0,1.00,"5564,1",maior,1,15,1
5564,5300108,2010-01-01,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,1.0,1.00,1.00,1.0,1.00,"5565,1",menor,0,15,1
0,1100015,2010-01-01,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,1.0,1.00,1.00,1.0,1.00,"1,1",maior,1,15,1

In [23]:
df_duplo.duplicated(subset=['nome_mun', 'nome_micro', 'nome_meso'])

0       False
1       False
2       False
3       False
4       False
        ...
5561    False
5562    False
5563    False
5564    False
0        True
Length: 5566, dtype: bool

In [24]:
df_duplo = df_duplo.drop_duplicates(subset=['nome_mun', 'nome_micro', 'nome_meso'])
df_duplo

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado,diferenca,dia
0,1100015,2010-01-01,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,1.0,1.00,1.00,1.0,1.00,"1,1",maior,1,15,1
1,1100023,2010-01-01,Rondonia,ariquemes,ariquemes,leste rondoniense,73.36,1.91,19.20,20.53,...,1.0,1.00,0.60,1.0,1.00,"2,1",menor,0,15,1
2,1100031,2010-01-01,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,0.7,0.65,1.00,1.0,0.65,"3,1",maior,1,15,1
3,1100049,2010-01-01,Rondonia,cacoal,cacoal,leste rondoniense,74.27,1.90,14.30,15.38,...,1.0,1.00,0.62,1.0,1.00,"4,1",menor,0,15,1
4,1100056,2010-01-01,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,1.0,1.00,1.00,1.0,1.00,"5,1",maior,1,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010-01-01,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,1.0,1.00,1.00,1.0,0.71,"5561,1",maior,1,15,1
5561,5222054,2010-01-01,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,1.0,1.00,1.00,1.0,1.00,"5562,1",maior,1,15,1
5562,5222203,2010-01-01,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,1.0,1.00,1.00,1.0,1.00,"5563,1",maior,1,15,1
5563,5222302,2010-01-01,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,1.0,1.00,1.00,1.0,1.00,"5564,1",maior,1,15,1
5564,5300108,2010-01-01,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,1.0,1.00,1.00,1.0,1.00,"5565,1",menor,0,15,1

In [25]:
df.pivot_table(values="espvida", index="nome_meso", aggfunc="mean")

                                 espvida
nome_meso
agreste alagoano               69.404167
agreste paraibano              70.475152
agreste pernambucano           69.783803
agreste potiguar               70.356047
agreste sergipano              70.658889
...                                  ...
vale do mucuri                 72.481304
vale do paraíba paulista       75.087949
vale do rio doce               73.400882
vale são-franciscano da bahia  70.896667
zona da mata                   74.417887

[137 rows x 1 columns]

In [26]:
df.pivot_table(values=['espvida', 'fectot'], index="nome_meso", aggfunc="mean")

                                 espvida    fectot
nome_meso
agreste alagoano               69.404167  2.315833
agreste paraibano              70.475152  2.208636
agreste pernambucano           69.783803  2.151127
agreste potiguar               70.356047  2.437209
agreste sergipano              70.658889  2.135000
...                                  ...       ...
vale do mucuri                 72.481304  2.557391
vale do paraíba paulista       75.087949  1.970000
vale do rio doce               73.400882  2.093824
vale são-franciscano da bahia  70.896667  2.592222
zona da mata                   74.417887  1.885423

[137 rows x 2 columns]

In [27]:
df_filt = df[df['espvida'] > 75]

In [28]:
df_filt.pivot_table(values=['espvida', 'fectot'], index="nome_meso", aggfunc="mean")

                            espvida    fectot
nome_meso
araraquara                76.448000  1.805000
araçatuba                 76.170000  1.806667
assis                     76.110000  1.888000
baixadas                  75.545000  2.030000
bauru                     76.139677  2.030645
...                             ...       ...
vale do itajaí            77.258837  1.888605
vale do mucuri            76.020000  2.290000
vale do paraíba paulista  76.466667  1.865000
vale do rio doce          75.837857  1.967143
zona da mata              75.939434  1.831321

[79 rows x 2 columns]

In [ ]:
# df_filt.to_csv("saida.csv", index=False)

In [29]:
df.query('fectot > 2 or espvida > 75')

,mun,ano,uf,nome_mun,nome_micro,nome_meso,espvida,fectot,mort1,mort5,...,i_freq_prop,idhm,idhm_e,idhm_l,idhm_r,falsa,classificacao_fectot,mapeado,diferenca,dia
0,1100015,2010-01-01,Rondonia,alta floresta d'oeste,cacoal,leste rondoniense,70.75,2.24,23.80,25.49,...,1.0,1.00,1.0,1.0,1.00,"1,1",maior,1,15,1
2,1100031,2010-01-01,Rondonia,cabixi,colorado do oeste,leste rondoniense,70.39,2.15,24.80,26.58,...,0.7,0.65,1.0,1.0,0.65,"3,1",maior,1,15,1
4,1100056,2010-01-01,Rondonia,cerejeiras,colorado do oeste,leste rondoniense,72.94,2.12,18.10,19.42,...,1.0,1.00,1.0,1.0,1.00,"5,1",maior,1,15,1
6,1100072,2010-01-01,Rondonia,corumbiara,colorado do oeste,leste rondoniense,71.45,2.29,21.90,23.45,...,1.0,1.00,0.0,1.0,0.63,"7,1",maior,1,15,1
7,1100080,2010-01-01,Rondonia,costa marques,guajará-mirim,madeira-guaporé,70.04,2.72,25.80,27.66,...,1.0,1.00,0.0,1.0,1.00,"8,1",maior,1,15,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5560,5222005,2010-01-01,Goias,vianópolis,pires do rio,sul goiano,74.10,2.10,14.40,17.04,...,1.0,1.00,1.0,1.0,0.71,"5561,1",maior,1,15,1
5561,5222054,2010-01-01,Goias,vicentinópolis,meia ponte,sul goiano,73.25,2.29,15.70,18.51,...,1.0,1.00,1.0,1.0,1.00,"5562,1",maior,1,15,1
5562,5222203,2010-01-01,Goias,vila boa,entorno de brasília,leste goiano,74.07,2.64,14.50,17.09,...,1.0,1.00,1.0,1.0,1.00,"5563,1",maior,1,15,1
5563,5222302,2010-01-01,Goias,vila propício,entorno de brasília,leste goiano,73.09,2.67,15.90,18.80,...,1.0,1.00,1.0,1.0,1.00,"5564,1",maior,1,15,1
5564,5300108,2010-01-01,Distrito Federal,brasília,brasília,distrito federal,77.35,1.75,14.01,15.85,...,1.0,1.00,1.0,1.0,1.00,"5565,1",menor,0,15,1